#!/usr/bin/env python3
"""Render the market and capability objects of the model from what the crawlers declare.

    ./gradlew :server:dumpCapabilities -q > docs/model/markets.json
    python3 docs/model/generate_markets.py

The document it writes is generated, so a market gaining pagination or losing its native filters
appears in the model by rebuilding rather than by remembering to edit it.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).parent
DUMP = HERE / "markets.json"
OUT = HERE / "sdoc" / "04-markets.sdoc"

# One capability object per interface in server/.../crawler/Capabilities.kt. The flags come from the
# dump; only the wording lives here.
CAPABILITIES = [
    ("CAP-PAGES", "Fetches every page", "FetchesEveryPage", "paginates",
     "Goes past the first page of results. A market without it answers with one page, so its "
     "share of a search is capped by however many the site puts on a page."),
    ("CAP-NATIVE", "Filters at the source", "FiltersAtTheSource", "nativeCriteria",
     "Turns vehicle criteria into the market's own URL parameters, so the site does the narrowing. "
     "Everything a market does not take natively is filtered after the fetch, over whatever the "
     "first pages happened to contain."),
    ("CAP-SOLD", "Knows what sold", "HasSoldListings", "soldListings",
     "Answers with listings that already sold, which is the only source of a real price history."),
    ("CAP-RELATED", "Suggests related searches", "SuggestsRelatedSearches", "relatedSearches",
     "Prints the searches it considers related — the market's own vocabulary for the thing, which "
     "is where query expansion gets its terms."),
    ("CAP-AGE", "Knows an ad's age", "KnowsListingAge", "listingAge",
     "Says when the ad was posted, so how long a thing has been for sale can be shown."),
    ("CAP-PLACE", "Knows where the thing is", "KnowsLocation", "location",
     "Carries a place, so a distance from the searcher can be measured and sorted by."),
    ("CAP-SPECS", "Carries specs on the detail page", "HasDetailSpecs", "detailSpecs",
     "Holds fields the result card omits — power, gearbox, doors, emission class — worth one extra "
     "fetch when a filter needs a field the card does not carry."),
    ("CAP-CURRENCY", "Prices in its own currency", "PricesInOwnCurrency", "currency",
     "Lists in something other than the euro, so amounts must be converted before being compared."),
]

CRITERION_WORDS = {
    "YEAR": "year", "MILEAGE": "mileage", "PRICE": "price", "POWER": "power",
    "GEARBOX": "gearbox", "FUEL": "fuel", "BODY": "body", "CONDITION": "condition",
    "SELLER": "seller",
}


def has(market, flag):
    value = market[flag]
    return bool(value) if not isinstance(value, list) else len(value) > 0


def market_statement(market):
    parts = []
    if market["nativeCriteria"]:
        criteria = ", ".join(CRITERION_WORDS.get(c, c.lower()) for c in market["nativeCriteria"])
        parts.append(f"Filters {criteria} in its own URL; everything else is filtered afterwards.")
    else:
        parts.append("Applies no filter of its own, so every criterion is applied after the fetch.")
    if market["paginates"]:
        limit = market["pageLimit"]
        parts.append(f"Fetches up to {limit} pages." if limit else "Fetches every page a search asks for.")
    else:
        parts.append("Answers with the first page only.")
    if market["currency"]:
        parts.append(f"Prices in {market['currency']}, converted before comparison.")
    return " ".join(parts)


def escape(text):
    return text.replace("\n", " ").strip()


def main():
    dump = json.loads(DUMP.read_text())
    lines = [
        "[DOCUMENT]",
        "TITLE: Markets",
        "OPTIONS:",
        "  MARKUP: Text",
        "",
        "[GRAMMAR]",
        "IMPORT_FROM_FILE: grammar.sgra",
        "",
        "[TEXT]",
        "STATEMENT: >>>",
        f"{len(dump['markets'])} markets are crawled. What each can do is declared by its crawler in",
        "the code and read from there, so this page cannot quietly stop being true.",
        "",
        "This document is generated by docs/model/generate_markets.py. Edit the crawlers, not this file.",
        "<<<",
        "",
        "[SECTION]",
        "TITLE: What a market can do",
        "",
    ]

    for uid, title, interface, flag, statement in CAPABILITIES:
        holders = [m for m in dump["markets"] if has(m, flag)]
        lines += [
            "[CAPABILITY]",
            f"UID: {uid}",
            f"TITLE: {title}",
            "STATEMENT: >>>",
            statement,
            "",
            f"{len(holders)} of {len(dump['markets'])} markets: "
            + (", ".join(m["name"] for m in holders) if holders else "none"),
            "<<<",
            f"INTERFACE: {interface}",
            "",
        ]

    lines += ["[/SECTION]", "", "[SECTION]", "TITLE: The markets", ""]

    for market in sorted(dump["markets"], key=lambda m: m["name"].lower()):
        lines += [
            "[MARKET]",
            f"UID: MARKET-{market['id'].replace('_', '-')}",
            f"TITLE: {market['name']}",
            "STATEMENT: >>>",
            escape(market_statement(market)),
            "",
            f"{market['baseUrl']}",
            "<<<",
        ]
        if market["country"]:
            lines.append(f"COUNTRY: {market['country']}")
        lines += [
            f"LANGUAGE: {market['searchLanguage']}",
            f"CRAWLER: {market['crawler']}",
            "STATUS: Crawled",
        ]
        held = [uid for uid, _, _, flag, _ in CAPABILITIES if has(market, flag)]
        if held:
            lines.append("RELATIONS:")
            for uid in held:
                lines += ["- TYPE: Parent", f"  VALUE: {uid}", "  ROLE: Can"]
        lines.append("")

    for platform in dump["withoutCrawler"]:
        lines += [
            "[MARKET]",
            f"UID: MARKET-{platform.replace('_', '-')}",
            f"TITLE: {platform}",
            "STATEMENT: >>>",
            "Offered in the app as a market to search, and no crawler exists for it, so selecting it",
            "adds nothing and says nothing.",
            "<<<",
            "STATUS: Offered without a crawler",
            "",
        ]

    lines += ["[/SECTION]", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {len(dump['markets'])} markets, {len(CAPABILITIES)} capabilities")


if __name__ == "__main__":
    main()
